# MySQL.  Versions 5.0+ are recommended.


<% if ENV['OPENSHIFT_MYSQL_DB_HOST'] %>
mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  
<% else %>      
      
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: capp_development

test:
  <<: *default
  database: capp_test

production:
  <<: *default
  database: capp_production
  username: capp
  password: <%= ENV['CAPP_DATABASE_PASSWORD'] %>


<% end %>