# MySQL.  Versions 5.0+ are recommended.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: capp_development

test:
  <<: *default
  database: capp_test

production:
  adapter: postgresql
  host: localhost
  database: capps_production
  username: capp
  password: <%= ENV['CAPPS_DATABASE_PASSWORD'] %>

